### ISSUE TITLE
file permissions issues when using Learn IDE

### ISSUE THREAD

**Issue by mikeries** [learn-co-curriculum/sql-database-basics-readme#14]
I used the Learn IDE tree to create a folder, and within it a file 01_create_cats_table.sql.  Unfortunately, when you use the file tree to create folders and files, the owner is root, and you cannot code along in the terminal in this lesson or the next because the terminal does not have root access to create or edit the database.

The workaround is to create the folders and files using the terminal so that they have the correct permissions.

By the way, I ran into this issue with the CLI Data Gem project as well, and it is probably the same for many labs.  Maybe just put a note in the relevant labs to be on the lookout for this?

**Comment by sgharms** [comment]
@mikeries 

I'll be sending this request over the Learn IDE team for them to verify this is no longer an issue.

Thanks for the help,

Steven
