### ISSUE TITLE
Awkward Sentence - please review

### ISSUE THREAD

**Issue by michaelwahlin** [learn-co-curriculum/sql-database-basics-readme#15]
Every table we create, regardless of the other column names and data types, should be defined with an id INTEGER PRIMARY KEY column + data type.

Perhaps write as:

Every table we create, regardless of the other column names and data types, should be defined with an id INTEGER PRIMARY KEY column, including data type and primary key designation.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thanks for your contribution! 💙
