### ISSUE TITLE
GitHub link doesn't work

### ISSUE THREAD

**Issue by mmmeyers** [learn-co-curriculum/sql-database-basics-readme#8]
The GitHub link at the top of the page goes to https://github.com/learn-co-students/sql-database-basics-readme-v-000, which is a 'Page not found.' 

Looks like the URL for this lesson is https://github.com/learn-co-curriculum/sql-database-basics-readme

**Comment by AnnJohn** [comment]
Hi @mmmeyers sorry for the issue. Yes, you're right, the correct canonical URL is that second url you have there. However, for this lesson, you don't need to fork and clone the repo. Thanks!
